.TH DJPEG-XR 1 "15 June 2011"
.SH NAME
djpeg-xr \- decompress a JPEG-XR file to an image file
.SH SYNOPSIS
.B djpeg-xr
[
.I options
]
[
.I filename
]
.LP
.SH DESCRIPTION
.LP
.B djpeg-xr
decompresses the named JPEG-XR file, or the standard input if no file is named,
and produces an image file on the standard output. TODO - list supported formats.
.SH OPTIONS
TODO - list supported options.
.SH AUTHOR
Chris Harding
